---
logging:
  level:
    com.szss: DEBUG
    com.ibatis: DEBUG
    org.springframework: WARN
    org.springframework.security: DEBUG
    org.springframework.cloud: WARN
    org.springframework.web: WARN

server:
  port: 9001

spring:
  profiles: dev
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://localhost:3306/uaa
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: admin
    password: 123456

ribbon:
  eureka:
    enabled: true



---
server:
  port: 9001

spring:
  profiles: docker
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://mysql:3306/uaa
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    addresses: rabbitmq1:5672,rabbitmq2:5672,rabbitmq3:5672
    username: admin
    password: 123456

ribbon:
  eureka:
    enabled: true
