---
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: WARN

server:
  port: 8080

spring:
  profiles: dev
  aop:
    proxy-target-class: true
  rabbitmq:
     host: 192.168.99.100
     port: 5672
     username: admin
     password: 123456

zuul:
  routes:
    auth-service: /auth/**
    platform-service: /platform/**

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:7777/uaa/oauth/token
      userAuthorizationUri: http://localhost:7777/uaa/oauth/authorize
      clientId: client
      clientSecret: secret
    resource:
      userInfoUri: http://localhost:7777/uaa/user
      preferTokenInfo: false
  sessions: ALWAYS

---
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: WARN

server:
  port: 8080

spring:
  profiles: docker
  aop:
    proxy-target-class: true
  rabbitmq:
    addresses: rabbitmq1:5672,rabbitmq2:5672,rabbitmq3:5672
    username: admin
    password: 123456

zuul:
  routes:
    auth-service: /auth/**
    platform-service: /platform/**

security:
  oauth2:
    client:
      accessTokenUri: http://auth-service:7777/uaa/oauth/token
      userAuthorizationUri: http://auth-service:7777/uaa/oauth/authorize
      clientId: client
      clientSecret: secret
    resource:
      userInfoUri: http://auth-service:7777/uaa/user
      preferTokenInfo: false
  sessions: ALWAYS
